[package]
name = "iam0-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Data 
num-bigint = "0.4.5"

# Error management
thiserror = "1"
anyhow = "1"

# Tracing
tracing = "0.1.40"
