[package]
name = "iam0-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7"
tokio = { version = "1.37", features = ["full"] }

dotenv = "0.15.0"

serde = "1"
serde_json = "1"

thiserror = "1"
anyhow = "1"

tracing = "0.1.40"
